"""The home of all project specific strings and values that are better to be set in one place than to be scattered around the code."""
from pathlib import Path

## Project values
AIR_GAP = 40
DRIP_STOP = 5
PURGE_VOLUME = 20
RANDOM_FLAG = False # Set to True to randomize the order of the experiments

## Flag to use only local paths
USE_LOCAL_PATHS = True

## Define local repository path
LOCAL_REPO_PATH = Path.cwd()

## Define network path
NETWORK_PATH = Path(r"\\engnas.bu.edu\research\eng_research_kablab\Shared Resources\PANDA\\")

## Project File Names
MILL_CONFIG_FILE_NAME = "mill_config.json"
PROJECT_LIST_FILE_NAME = "project_list.csv"
QUEUE_FILE_NAME = "queue.csv"
SLACK_TICKETS_FILE_NAME = "slack_ticket_tracker.csv"
STOCK_STATUS_FILE_NAME = "stock_status.json"
WASTE_STATUS_FILE_NAME = "waste_status.json"
WELL_STATUS_FILE_NAME = "well_status.json"
WELL_TYPE_FILE_NAME = "well_type.csv"
WELLPLATE_CONFIG_FILE_NAME = "wellplate_location.json"
WELL_HISTORY = "well_history.csv"

## Project directory names
CODE = "code"
CONFIG = "config"
DATA = "data"
EXPERIMENT_INBOX = "experiments_inbox"
EXPERIMENT_QUEUE = "experiment_queue"
EXPERIMENTS_COMPLETED = "experiments_completed"
EXPERIMENTS_ERROR = "experiments_error"
LOGS = "logs"
STATUS = "system state"

## Build complete paths for each project directory or file
if USE_LOCAL_PATHS:
    # Directories
    PATH_TO_CODE = LOCAL_REPO_PATH / CODE
    PATH_TO_STATUS = PATH_TO_CODE / STATUS
    PATH_TO_CONFIG = PATH_TO_CODE / CONFIG
    PATH_TO_COMPLETED_EXPERIMENTS = PATH_TO_CODE / EXPERIMENTS_COMPLETED
    PATH_TO_ERRORED_EXPERIMENTS = PATH_TO_CODE / EXPERIMENTS_ERROR
    PATH_TO_DATA = LOCAL_REPO_PATH / DATA
    PATH_TO_LOGS = PATH_TO_CODE / LOGS
    PATH_TO_EXPERIMENT_INBOX = PATH_TO_CODE / EXPERIMENT_INBOX
    PATH_TO_EXPERIMENT_QUEUE = PATH_TO_CODE / EXPERIMENT_QUEUE
    PATH_TO_NETWORK_DATA = LOCAL_REPO_PATH / DATA
    PATH_TO_NETWORK_LOGS = PATH_TO_CODE / LOGS
    PATH_TO_NETWORK_STATUS = PATH_TO_CODE / STATUS

    # Files
    PATH_TO_MILL_CONFIG = PATH_TO_CONFIG / MILL_CONFIG_FILE_NAME
    PATH_TO_LOCAL_WELL_HX = PATH_TO_DATA / WELL_HISTORY
    PATH_TO_NETWORK_WELL_HX = PATH_TO_NETWORK_DATA / WELL_HISTORY
    PATH_TO_NETWORK_QUEUE = PATH_TO_NETWORK_STATUS / QUEUE_FILE_NAME
    PATH_TO_NETWORK_STOCK_STATUS = PATH_TO_NETWORK_STATUS / STOCK_STATUS_FILE_NAME
    PATH_TO_NETWORK_WASTE_STATUS = PATH_TO_NETWORK_STATUS / WASTE_STATUS_FILE_NAME
    PATH_TO_NETWORK_SLACK_TICKETS = PATH_TO_NETWORK_LOGS / SLACK_TICKETS_FILE_NAME
else:
    # Directories
    PATH_TO_CODE = NETWORK_PATH / CODE 
    PATH_TO_STATUS = NETWORK_PATH / STATUS
    PATH_TO_CONFIG = NETWORK_PATH / CONFIG
    PATH_TO_COMPLETED_EXPERIMENTS = NETWORK_PATH / EXPERIMENTS_COMPLETED
    PATH_TO_ERRORED_EXPERIMENTS = NETWORK_PATH / EXPERIMENTS_ERROR
    PATH_TO_DATA = NETWORK_PATH / DATA
    PATH_TO_LOGS = NETWORK_PATH / LOGS
    PATH_TO_EXPERIMENT_INBOX = NETWORK_PATH / EXPERIMENT_INBOX
    PATH_TO_EXPERIMENT_QUEUE = NETWORK_PATH / EXPERIMENT_QUEUE
    PATH_TO_NETWORK_DATA = NETWORK_PATH / DATA
    PATH_TO_NETWORK_LOGS = NETWORK_PATH / LOGS
    PATH_TO_NETWORK_STATUS = NETWORK_PATH / STATUS

    #Files
    PATH_TO_MILL_CONFIG = PATH_TO_CONFIG / MILL_CONFIG_FILE_NAME
    PATH_TO_LOCAL_WELL_HX = PATH_TO_DATA / WELL_HISTORY
    PATH_TO_NETWORK_WELL_HX = PATH_TO_NETWORK_DATA / WELL_HISTORY
    PATH_TO_NETWORK_QUEUE = PATH_TO_NETWORK_STATUS / QUEUE_FILE_NAME
    PATH_TO_NETWORK_STOCK_STATUS = PATH_TO_NETWORK_STATUS / STOCK_STATUS_FILE_NAME
    PATH_TO_NETWORK_WASTE_STATUS = PATH_TO_NETWORK_STATUS / WASTE_STATUS_FILE_NAME
    PATH_TO_NETWORK_SLACK_TICKETS = PATH_TO_NETWORK_LOGS / SLACK_TICKETS_FILE_NAME

## Validate that all paths exist and create them if they don't
for path in [
    PATH_TO_STATUS,
    PATH_TO_CONFIG,
    PATH_TO_COMPLETED_EXPERIMENTS,
    PATH_TO_ERRORED_EXPERIMENTS,
    PATH_TO_DATA,
    PATH_TO_LOGS,
    PATH_TO_EXPERIMENT_INBOX,
    PATH_TO_EXPERIMENT_QUEUE,
    PATH_TO_NETWORK_DATA,
    PATH_TO_NETWORK_LOGS,
    PATH_TO_NETWORK_STATUS,
]:
    if not path.exists():
        print(f"Creating {path}")
        path.mkdir()
        print(f"Created {path}")

## Validate that all files exist and create them if they don't
for file in [
    MILL_CONFIG_FILE_NAME,
    WELLPLATE_CONFIG_FILE_NAME,
    PROJECT_LIST_FILE_NAME,
    QUEUE_FILE_NAME,
    STOCK_STATUS_FILE_NAME,
    WASTE_STATUS_FILE_NAME,
    WELL_STATUS_FILE_NAME,
    PATH_TO_LOCAL_WELL_HX,
    PATH_TO_NETWORK_WELL_HX,
    PATH_TO_NETWORK_QUEUE,
    PATH_TO_NETWORK_STOCK_STATUS,
    PATH_TO_NETWORK_WASTE_STATUS,
    PATH_TO_NETWORK_SLACK_TICKETS,
]:
    file_path = PATH_TO_STATUS / file
    if not file_path.exists():
        print(f"Creating {file_path}")
        file_path.touch()
        print(f"Created {file_path}")
