"""add drop_coordinates to tipracks

Revision ID: e632805d8a0f
Revises: 
Create Date: 2025-08-11 14:33:00.594399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision: str = 'e632805d8a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panda_tip_hx', sa.Column('drop_coordinates', sa.JSON(), nullable=True))
    op.add_column('panda_tipracks', sa.Column('drop_coordinates', sa.JSON(), nullable=True))

    bind = op.get_bind()
    session = Session(bind=bind)

    # Example: set empty dicts to avoid None checks everywhere
    session.execute(sa.text(
        "UPDATE panda_tip_hx SET drop_coordinates = '{}' WHERE drop_coordinates IS NULL"
    ))
    session.execute(sa.text(
        "UPDATE panda_tipracks SET drop_coordinates = '{}' WHERE drop_coordinates IS NULL"
    ))
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_unique_current'), 'panda_wellplates', ['current', 'panda_unit_id'], unique=1, sqlite_where=sa.text('current = 1'))
    op.alter_column('panda_wellplates', 'name',
               existing_type=sa.NullType(),
               nullable=True)
    op.alter_column('panda_wellplates', 'bottom',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('panda_wellplates', 'top',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('panda_wellplates', 'height',
               existing_type=sa.NullType(),
               nullable=True)
    op.alter_column('panda_wellplates', 'base_thickness',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplates', 'coordinates',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_wellplates', 'panda_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_wellplates', 'image_height',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_wellplates', 'echem_height',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('(-70)'))
    op.alter_column('panda_wellplates', 'cols',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(ABCDEFGH)'))
    op.alter_column('panda_wellplates', 'rows',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(13)'))
    op.alter_column('panda_wellplates', 'orientation',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_wellplates', 'a1_y',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('(-78.5)'))
    op.alter_column('panda_wellplates', 'a1_x',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('(-221.75)'))
    op.alter_column('panda_wellplates', 'current',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_wellplates', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'base_thickness',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('panda_wellplate_types', 'capacity_ul',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'max_liquid_height_mm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'y_offset',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'x_offset',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'gasket_height_mm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'gasket_width_mm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'gasket_length_mm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'x_spacing',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'y_spacing',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'radius_mm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'shape',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'cols',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(12)'))
    op.alter_column('panda_wellplate_types', 'rows',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(ABCDEFGH)'))
    op.alter_column('panda_wellplate_types', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'gasket',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'substrate',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_wellplate_types', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('panda_well_hx', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_well_hx', 'top',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('panda_well_hx', 'height',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('6'))
    op.alter_column('panda_well_hx', 'base_thickness',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('panda_well_hx', 'coordinates',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_well_hx', 'bottom',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('panda_well_hx', 'contents',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_well_hx', 'volume_height',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('panda_well_hx', 'contamination',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_well_hx', 'capacity',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(150)'))
    op.alter_column('panda_well_hx', 'volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_well_hx', 'radius',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(3.25)'))
    op.alter_column('panda_well_hx', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_well_hx', 'status_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_well_hx', 'dead_volume',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.01)'))
    op.alter_column('panda_well_hx', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_well_hx', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_well_hx', 'experiment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_well_hx', 'well_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_well_hx', 'plate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_vials', 'panda_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_vials', 'bottom',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('panda_vials', 'top',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('panda_vials', 'volume_height',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('panda_vials', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_vials', 'active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('panda_vials', 'dead_volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(1000.0)'))
    op.alter_column('panda_vials', 'base_thickness',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('panda_vials', 'coordinates',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_vials', 'contamination',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_vials', 'capacity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(20000.0)'))
    op.alter_column('panda_vials', 'volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(20000.0)'))
    op.alter_column('panda_vials', 'radius',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(14.0)'))
    op.alter_column('panda_vials', 'height',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(57.0)'))
    op.alter_column('panda_vials', 'density',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_vials', 'concentration',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_vials', 'viscosity_cp',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('panda_vials', 'contents',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_vials', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_vials', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_vials', 'position',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_vials', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('panda_users', sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('panda_users', sa.Column('full', sa.NullType(), sa.Computed("first || ' ' || last", persisted=True), nullable=True))
    op.alter_column('panda_users', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_users', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_users', 'last',
               existing_type=sa.NullType(),
               nullable=True)
    op.alter_column('panda_users', 'first',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('panda_users', 'created')
    op.alter_column('panda_user_projects', 'timestamp',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_user_projects', 'current',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('panda_user_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_user_projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_units', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_units', 'version',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('panda_units', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('panda_tipracks', 'cols',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(12)'))
    op.alter_column('panda_tipracks', 'rows',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'ABCDEFGH'"))
    op.alter_column('panda_tipracks', 'orientation',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_tipracks', 'current',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
    op.alter_column('panda_tipracks', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('panda_tipracks', 'name')
    op.drop_column('panda_tipracks', 'bottom')
    op.drop_column('panda_tipracks', 'top')
    op.drop_column('panda_tipracks', 'height')
    op.drop_column('panda_tipracks', 'base_thickness')
    op.drop_column('panda_tipracks', 'coordinates')
    op.drop_column('panda_tipracks', 'drop_coordinates')
    op.alter_column('panda_tiprack_types', 'shape',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_tiprack_types', 'rows',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_tiprack_types', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('panda_tip_hx', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_tip_hx', 'status_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_tip_hx', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_tip_hx', 'tip_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('panda_tip_hx', 'name')
    op.drop_column('panda_tip_hx', 'top')
    op.drop_column('panda_tip_hx', 'height')
    op.drop_column('panda_tip_hx', 'base_thickness')
    op.drop_column('panda_tip_hx', 'coordinates')
    op.drop_column('panda_tip_hx', 'bottom')
    op.drop_column('panda_tip_hx', 'contents')
    op.drop_column('panda_tip_hx', 'volume_height')
    op.drop_column('panda_tip_hx', 'dead_volume')
    op.drop_column('panda_tip_hx', 'contamination')
    op.drop_column('panda_tip_hx', 'capacity')
    op.drop_column('panda_tip_hx', 'volume')
    op.drop_column('panda_tip_hx', 'radius_mm')
    op.drop_column('panda_tip_hx', 'tip_length')
    op.alter_column('panda_system_status', 'panda_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_system_status', 'status_time',
               existing_type=sa.String(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_system_status', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_system_status', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_system_status', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'panda_slack_tickets', type_='unique')
    op.create_index(op.f('msg_id_index'), 'panda_slack_tickets', ['msg_id', 'timestamp'], unique=False)
    op.alter_column('panda_slack_tickets', 'db_timestamp',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_slack_tickets', 'addressed_timestamp',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_slack_tickets', 'timestamp',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_slack_tickets', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_slack_tickets', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_slack_tickets', 'msg_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('panda_protocols', 'filepath',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_protocols', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_protocols', 'project',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_protocols', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('panda_projects', 'added',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_projects', 'project_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_projects', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('panda_pipette_log', 'panda_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_pipette_log', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_pipette_log', 'volume_ml',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('panda_pipette_log', 'volume_ul',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('panda_pipette_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_unique_active'), 'panda_pipette', ['active'], unique=False, sqlite_where=sa.text('active = 1'))
    op.alter_column('panda_pipette', 'panda_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_pipette', 'uses',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_pipette', 'active',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_pipette', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_pipette', 'contents',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_pipette', 'volume_ml',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('panda_pipette', 'volume_ul',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('panda_pipette', 'capacity_ml',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('panda_pipette', 'capacity_ul',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('panda_pipette', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'models_current_rmse',
               existing_type=sa.Float(precision=18, asdecimal=8),
               type_=sa.REAL(precision=18, asdecimal=8),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'standard_deviation',
               existing_type=sa.Float(precision=18, asdecimal=8),
               type_=sa.REAL(precision=18, asdecimal=8),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'predicted_response',
               existing_type=sa.Float(precision=18, asdecimal=8),
               type_=sa.REAL(precision=18, asdecimal=8),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'edot_concentration',
               existing_type=sa.Float(precision=18, asdecimal=8),
               type_=sa.REAL(precision=18, asdecimal=8),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 't_dep',
               existing_type=sa.Float(precision=18, asdecimal=8),
               type_=sa.REAL(precision=18, asdecimal=8),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'v_dep',
               existing_type=sa.Float(precision=18, asdecimal=8),
               type_=sa.REAL(precision=18, asdecimal=8),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'best_test_point',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'best_test_point_original',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_ml_pedot_best_test_points', 'best_test_point_scalar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_generators', 'filepath',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_generators', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(None, 'panda_experiments', 'panda_units', ['panda_unit_id'], ['id'])
    op.alter_column('panda_experiments', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_experiments', 'created',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_experiments', 'panda_version',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
    op.alter_column('panda_experiments', 'needs_analysis',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('panda_experiments', 'filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('panda_experiments', 'protocol_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_experiments', 'experiment_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'panda_experiment_results', type_='foreignkey')
    op.alter_column('panda_experiment_results', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_experiment_results', 'created',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_experiment_results', 'context',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_experiment_results', 'result_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_experiment_results', 'result_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('panda_experiment_results', 'experiment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('panda_experiment_results', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'panda_experiment_parameters', type_='foreignkey')
    op.alter_column('panda_experiment_parameters', 'updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_experiment_parameters', 'created',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('panda_experiment_parameters', 'parameter_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_experiment_parameters', 'parameter_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('panda_experiment_parameters', 'experiment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('panda_mill_tools',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('offset', sa.TEXT(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panda_labware',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.Column('max_volume_ul', sa.NullType(), nullable=True),
    sa.Column('shape', sa.REAL(), nullable=False),
    sa.Column('length_mm', sa.REAL(), nullable=False),
    sa.Column('width_mm', sa.REAL(), nullable=False),
    sa.Column('height_mm', sa.REAL(), nullable=False),
    sa.Column('depth_mm', sa.REAL(), nullable=False),
    sa.Column('total_length_mm', sa.REAL(), nullable=False),
    sa.Column('diameter', sa.REAL(), nullable=False),
    sa.Column('x_size_mm', sa.REAL(), nullable=True),
    sa.Column('y_size_mm', sa.REAL(), nullable=False),
    sa.Column('x_spacing_mm', sa.REAL(), nullable=False),
    sa.Column('y_spacing_mm', sa.REAL(), nullable=False),
    sa.Column('x_offset_mm', sa.REAL(), nullable=False),
    sa.Column('y_offset_mm', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panda_potentiostat_readouts',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.Column('interface', sa.TEXT(), nullable=False),
    sa.Column('technique', sa.TEXT(), nullable=False),
    sa.Column('readout_values', sa.TEXT(), nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['panda_experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panda_vials_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('old_id', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.TEXT(), nullable=True),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('contents', sa.TEXT(), nullable=True),
    sa.Column('viscosity_cp', sa.REAL(), nullable=True),
    sa.Column('concentration', sa.REAL(), nullable=True),
    sa.Column('density', sa.REAL(), nullable=True),
    sa.Column('height', sa.REAL(), server_default=sa.text('(57.0)'), nullable=True),
    sa.Column('radius', sa.REAL(), server_default=sa.text('(14.0)'), nullable=True),
    sa.Column('volume', sa.REAL(), server_default=sa.text('(20000.0)'), nullable=True),
    sa.Column('capacity', sa.REAL(), server_default=sa.text('(20000.0)'), nullable=True),
    sa.Column('contamination', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('coordinates', sa.TEXT(), nullable=True),
    sa.Column('base_thickness', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('dead_volume', sa.REAL(), server_default=sa.text('(1000.0)'), nullable=True),
    sa.Column('volume_height', sa.REAL(), nullable=True),
    sa.Column('bottom', sa.REAL(), nullable=True),
    sa.Column('top', sa.REAL(), nullable=True),
    sa.Column('updated', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('panda_unit_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panda_potentiostat_techniques',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('technique', sa.TEXT(), nullable=False),
    sa.Column('technique_description', sa.TEXT(), nullable=True),
    sa.Column('technique_params', sqlite.JSON(), nullable=True),
    sa.Column('gamry_1010T', sa.BOOLEAN(), nullable=False),
    sa.Column('gamry_1010B', sa.BOOLEAN(), nullable=False),
    sa.Column('gamry_1010E', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
