from venv import create
from sqlalchemy import Column, Integer, BigInteger, Text, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()

class Experiments(Base):
    """
    Experiments are the core of the system.

    They are used to store all the information about a single experiment, such as
    the project it belongs to, the protocol used, the well type, and the system
    version that ran the experiment.
    """
    __tablename__ = 'experiments'

    id = Column(Integer, primary_key=True, autoincrement=True)
    experiment_id = Column(BigInteger)
    project_id = Column(Integer, ForeignKey('projects.id'))
    project_campaign_id = Column(Integer)
    well_type = Column(Integer, ForeignKey('well_types.id'))
    protocol_id = Column(Integer, ForeignKey('protocols.id'))
    pin = Column(Text, ForeignKey('system_versions.pin'))
    experiment_type = Column(Integer)
    jira_issue_key = Column(Text)
    created = Column(DateTime)
    updated = Column(DateTime)
    priority = Column(Integer, default=0)
    process_type = Column(Integer, default=0)
    filename = Column(Text, default=None)

    # Relationships (optional)
    project = relationship("Project", back_populates="experiments")
    protocol = relationship("Protocol", back_populates="experiments")
    well_type = relationship("WellType", back_populates="experiments")
    system_version = relationship("SystemVersion", back_populates="experiments")

class ExperimentParameters(Base):
    """
    Experiment parameters are the settings used to run an experiment.

    This table stores the parameters used for each experiment.
    """
    __tablename__ = 'experiment_parameters'

    id = Column(Integer, primary_key=True, autoincrement=True)
    experiment_id = Column(Integer, ForeignKey('experiments.id'))
    parameter_name = Column(Text)
    parameter_value = Column(Text)
    created = Column(DateTime)
    updated = Column(DateTime)

    # Relationships (optional)
    experiment = relationship("Experiment", back_populates="parameters")

class ExperimentResults(Base):
    """
    Experiment results are the data generated by an experiment.

    This table stores the results of each experiment.
    """
    __tablename__ = 'experiment_results'

    id = Column(Integer, primary_key=True, autoincrement=True)
    experiment_id = Column(Integer, ForeignKey('experiments.id'))
    result_type = Column(Text)
    result_value = Column(Text)
    created = Column(DateTime)
    updated = Column(DateTime)

    # Relationships (optional)
    experiment = relationship("Experiment", back_populates="results")

class Project(Base):
    """
    Projects are a higher level of organization for experiments.
    
    They are used to group experiments together, and can also be used to limit
    access to certain experiments based on the project a user belongs to.
    """
    __tablename__ = 'projects'
    id = Column(Integer, primary_key=True)
    experiments = relationship("Experiment", back_populates="project")

class Protocol(Base):
    """
    Protocols are the instructions for running an experiment.

    This table stores the protocols and their filepaths.
    """
    __tablename__ = 'protocols'
    id = Column(Integer, primary_key=True)
    experiments = relationship("Experiment", back_populates="protocol")

class WellType(Base):
    """
    Well types are the different types of wells that can be used in an experiment.
    
    This table stores the well types and their descriptions.
    """
    __tablename__ = 'well_types'
    id = Column(Integer, primary_key=True)
    experiments = relationship("Experiment", back_populates="well_type")

class SystemVersion(Base):
    __tablename__ = 'system_versions'
    pin = Column(Text, primary_key=True)
    experiments = relationship("Experiment", back_populates="system_version")
